name: Build & Release

on:
  push:
    branches:
      - main
      - electron

jobs:
  build:
    name: Build (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Build for supported platforms
        # https://github.com/electron/electron-packager/blob/ebcbd439ff3e0f6f92fa880ff28a8670a9bcf2ab/src/targets.js#L9
        # 32-bit Linux unsupported as of 2019: https://www.electronjs.org/blog/linux-32bit-support
        os: [ macOS-latest ]
        # os: [ macOS-latest, ubuntu-latest, windows-latest ]
        # arch: [ x64, arm64 ]
        arch: [ arm64 ]
        # Publishing artifacts for multiple Windows architectures has
        # a bug which can cause the wrong architecture to be downloaded
        # for an update, so until that is fixed, only build Windows x64
        exclude:
        - os: windows-latest
          arch: arm64

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: desktop/package-lock.json
      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@d4873ceeec10de6275fecd1f94b6985369d40231
        with:
          deno-version: v1.29.1
      - name: Build Silver Bullet
        run: deno task build
      - name: Create Silver Bullet bundle
        run: deno task bundle
      - name: Set MacOS signing certs
        if: matrix.os == 'macOS-latest'
        run: chmod +x scripts/add-macos-cert.sh && ./scripts/add-macos-cert.sh
        env:
          MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
          MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
      # - name: Set Windows signing certificate
      #   if: matrix.os == 'windows-latest'
      #   continue-on-error: true
      #   id: write_file
      #   uses: timheuer/base64-to-file@v1
      #   with:
      #     fileName: 'win-certificate.pfx'
      #     encodedString: ${{ secrets.WINDOWS_CODESIGN_P12 }}
      - name: Install
        run: npm install
        working-directory: desktop
      - name: Make
        # if: startsWith(github.ref, 'refs/tags/')
        run: npm run make -- --arch=${{ matrix.arch }}
        working-directory: desktop
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #WINDOWS_CODESIGN_FILE: ${{ steps.write_file.outputs.filePath }}
          #WINDOWS_CODESIGN_PASSWORD: ${{ secrets.WINDOWS_CODESIGN_PASSWORD }}
      - name: Make
        # if: startsWith(github.ref, 'refs/tags/')
        run: npm run make -- --arch=${{ matrix.arch }}
        working-directory: desktop
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #WINDOWS_CODESIGN_FILE: ${{ steps.write_file.outputs.filePath }}
          #WINDOWS_CODESIGN_PASSWORD: ${{ secrets.WINDOWS_CODESIGN_PASSWORD }}
      - name: Rename artifacts
        if: matrix.os == 'macOS-latest'
        run: mv out/make/zip/*/*/*.zip out/silverbullet-macos-${{ matrix.arch }}.zip
        shell: bash
        working-directory: desktop
      - name: Release Mac
        uses: johnwbyrd/update-release@v1.0.0
        if: matrix.os == 'macOS-latest'
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: desktop/out/silverbullet-macos-${{ matrix.arch }}.zip
